spring.application.name=pagos
server.port=8088

# Configuración de Base de Datos PostgreSQL en Neon.tech
spring.datasource.url=jdbc:postgresql://ep-twilight-poetry-apjj90p1-pooler.c-7.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_e6NcSOiRo4Va
spring.datasource.driver-class-name=org.postgresql.Driver

# Crear/Actualizar tablas de forma automática
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true